name: sci
channels:
  - conda-forge
  - cytoflow
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - attrs=25.1.0=pyh71513ae_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - fonttools=4.55.8=py310hc74094e_0
  - liblapacke=3.9.0=28_hbb7bcf8_openblas
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - tbb=2022.0.0=h0cbf7ec_0
  - libopenvino-paddle-frontend=2024.6.0=h76e6831_3
  - unicodedata2=16.0.0=py310h078409c_0
  - bleach-with-css=6.2.0=h82add2a_4
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - bzip2=1.0.8=h99b78c6_7
  - rav1e=0.6.6=h69fbcac_2
  - libaec=1.1.3=hebf3989_0
  - libsodium=1.0.20=h99b78c6_0
  - nodejs=22.13.0=h02a13b7_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - libopenvino-onnx-frontend=2024.6.0=h76e6831_3
  - svt-av1=2.3.0=hf24288c_0
  - requests=2.32.3=pyhd8ed1ab_1
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - debugpy=1.8.12=py310h853098b_0
  - ipywidgets=8.1.5=pyhd8ed1ab_1
  - libcurl=8.11.1=h73640d1_0
  - libhwloc=2.11.2=default_hbce5d74_1001
  - tk=8.6.13=h5083fa2_1
  - aom=3.9.1=h7bae524_0
  - matplotlib-base=3.10.0=py310hadbac3a_0
  - referencing=0.36.2=pyh29332c3_0
  - libev=4.33=h93a5062_2
  - snappy=1.2.1=h98b9ce2_1
  - xorg-libxau=1.0.12=h5505292_0
  - brotli=1.1.0=hd74edd7_2
  - libopus=1.3.1=h27ca646_1
  - libintl=0.22.5=h8414b35_3
  - libtiff=4.7.0=h551f018_3
  - parso=0.8.4=pyhd8ed1ab_1
  - nbconvert-core=7.16.6=pyh29332c3_0
  - zlib=1.3.1=h8359307_2
  - typing_extensions=4.12.2=pyha770c72_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - pandas=2.2.3=py310hfd37619_1
  - libopenvino-tensorflow-lite-frontend=2024.6.0=h286801f_3
  - anyio=4.8.0=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - libjpeg-turbo=3.0.0=hb547adb_1
  - cached-property=1.5.2=hd8ed1ab_1
  - libzlib=1.3.1=h8359307_2
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - libblas=3.9.0=28_h10e41b3_openblas
  - openh264=2.5.0=h774163f_0
  - pugixml=1.14=h13dd4ca_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - pixman=0.44.2=h2f9eb0b_0
  - llvm-openmp=19.1.7=hdb05f8b_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - libopenvino-auto-batch-plugin=2024.6.0=h7f72211_3
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - c-ares=1.34.4=h5505292_0
  - ipykernel=6.29.5=pyh57ce528_0
  - libass=0.17.3=h16a287c_1
  - matplotlib=3.10.0=py310hb6292c7_0
  - libopenvino-ir-frontend=2024.6.0=hd3d436d_3
  - libopenvino-tensorflow-frontend=2024.6.0=he275e1d_3
  - jinja2=3.1.5=pyhd8ed1ab_0
  - libdeflate=1.23=hec38601_0
  - python=3.10.16=h870587a_1_cpython
  - zstd=1.5.6=hb46c0d2_0
  - h2=4.2.0=pyhd8ed1ab_0
  - libwebp-base=1.5.0=h2471fea_0
  - pthread-stubs=0.4=hd74edd7_1002
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - opencv=4.11.0=headless_py310h45b86b6_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - krb5=1.21.3=h237132a_0
  - cached_property=1.5.2=pyha770c72_1
  - libbrotlicommon=1.1.0=hd74edd7_2
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - cairo=1.18.2=h6a3b0d2_1
  - appnope=0.1.4=pyhd8ed1ab_1
  - liblapack=3.9.0=28_hc9a63f6_openblas
  - munkres=1.1.4=pyh9f0ad1d_0
  - x265=3.5=hbc6ce65_3
  - libcblas=3.9.0=28_hb3479ef_openblas
  - libopenvino-arm-cpu-plugin=2024.6.0=h97facdf_3
  - markupsafe=3.0.2=py310hc74094e_1
  - mistune=3.1.1=pyhd8ed1ab_0
  - hdf5=1.14.3=nompi_ha698983_109
  - jupyterlab=4.3.5=pyhd8ed1ab_0
  - fribidi=1.0.10=h27ca646_0
  - gmp=6.3.0=h7bae524_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - font-ttf-ubuntu=0.83=h77eed37_3
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - pyobjc-framework-cocoa=11.0=py310h4e4eb3c_0
  - setuptools=75.8.0=pyhff2d567_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - openexr=3.3.2=h360b6eb_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.4=pyhd8ed1ab_1
  - libffi=3.4.2=h3422bc3_5
  - libiconv=1.17=h0d3ecfb_2
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.13=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - six=1.17.0=pyhd8ed1ab_0
  - cffi=1.17.1=py310h497396d_0
  - pytz=2024.1=pyhd8ed1ab_0
  - fonts-conda-ecosystem=1=0
  - libasprintf=0.22.5=h8414b35_3
  - libavif16=1.1.1=h45b7238_2
  - dav1d=1.2.1=hb547adb_0
  - psutil=6.1.1=py310h078409c_0
  - qhull=2020.2=h420ef59_5
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_1
  - libopenvino=2024.6.0=h97facdf_3
  - libopencv=4.11.0=headless_py310hba82c68_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - kiwisolver=1.4.7=py310h7306fd8_0
  - json5=0.10.0=pyhd8ed1ab_1
  - pyyaml=6.0.2=py310hc74094e_2
  - fqdn=1.5.1=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - fontconfig=2.15.0=h1383a14_1
  - ipympl=0.9.6=pyhd8ed1ab_0
  - libpng=1.6.46=h3783ad8_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - contourpy=1.3.1=py310h7f4e7e6_0
  - libssh2=1.11.1=h9cc3647_0
  - libxcb=1.17.0=hdb1d25a_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - libglib=2.82.2=hdff4504_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - libgettextpo=0.22.5=h8414b35_3
  - pycparser=2.22=pyh29332c3_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - libbrotlidec=1.1.0=hd74edd7_2
  - comm=0.2.2=pyhd8ed1ab_1
  - terminado=0.18.1=pyh31c8845_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - brotli-bin=1.1.0=hd74edd7_2
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - yaml=0.2.5=h3422bc3_2
  - argon2-cffi-bindings=21.2.0=py310h493c2e1_5
  - bleach=6.2.0=pyh29332c3_4
  - tzdata=2025a=h78e105d_0
  - pillow=11.1.0=py310h61efb56_0
  - ca-certificates=2025.10.5
  - h11=0.14.0=pyhd8ed1ab_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - libvpx=1.14.1=h7bae524_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - lame=3.100=h1a8c8d9_1003
  - babel=2.17.0=pyhd8ed1ab_0
  - pyobjc-core=11.0=py310h4e4eb3c_0
  - libgfortran=5
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - jsonpointer=3.0.0=py310hbe9552e_1
  - py-opencv=4.11.0=headless_py310hbf97dbd_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - ipython=8.32.0=pyh907856f_0
  - graphite2=1.3.13=hebf3989_1003
  - pango=1.56.1=h73f1e88_0
  - ffmpeg=7.1.0=gpl_h7c3f5a8_109
  - openssl=3.5.4
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - zeromq=4.3.5=hc1bb282_7
  - httpcore=1.0.7=pyh29332c3_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - libopenvino-auto-plugin=2024.6.0=h7f72211_3
  - libopenvino-pytorch-frontend=2024.6.0=h286801f_3
  - idna=3.10=pyhd8ed1ab_1
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - libxml2=2.13.5=h178c5d8_1
  - libuv=1.50.0=h5505292_0
  - libprotobuf=5.28.3=h3bd63a1_1
  - send2trash=1.8.3=pyh31c8845_1
  - tornado=6.4.2=py310h078409c_0
  - librsvg=2.58.4=h266df6f_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - pyzmq=26.2.1=py310h6d25ecc_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - imath=3.1.12=h025cafa_0
  - libopenblas=0.3.28
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - beautifulsoup4=4.13.3=pyha770c72_0
  - freetype=2.12.1=hadb7bae_2
  - prompt-toolkit=3.0.50=pyha770c72_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - libsqlite=3.48.0=h3f77e49_1
  - rpds-py=0.22.3=py310hde4708a_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - brotli-python=1.1.0=py310hb4ad77e_2
  - webencodings=0.5.1=pyhd8ed1ab_3
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - pip=25.0=pyh8b19718_0
  - numpy=2.2.2
  - font-ttf-inconsolata=3.000=h77eed37_0
  - openjpeg=2.5.3=h8a3d83b_0
  - python_abi=3.10=5_cp310
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - urllib3=2.3.0=pyhd8ed1ab_0
  - fonts-conda-forge=1=0
  - liblzma=5.6.4=h39f12f2_0
  - libabseil=20240722.0=cxx17_h07bc746_4
  - hpack=4.1.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - pcre2=10.44=h297a79d_2
  - libgfortran5=14.2.0
  - jasper=4.2.4=h6c4e4ef_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - readline=8.2=h92ec313_1
  - lerc=4.0.0=h9a09cb3_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - libopenvino-hetero-plugin=2024.6.0=hd3d436d_3
  - ncurses=6.5=h5e97a16_3
  - libexpat=2.6.4=h286801f_0
  - libnghttp2=1.64.0=h6d7220d_0
  - certifi=2025.10.5
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - gdk-pixbuf=2.42.12=h7ddc832_0
  - zstandard=0.23.0=py310h2665a74_1
  - lcms2=2.16=ha0e7c42_0
  - x264=1!164.3095=h57fd34a_2
  - harfbuzz=10.2.0=ha0dd535_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - libcxx=19.1.7=ha82da77_0
  - blas[build=openblas]
prefix: /opt/anaconda3/envs/sci
